### PR TITLE
Add Cublas Support

### PR DESCRIPTION
**Pull request by TeslaCoder**
Add support for High Performance DGEMM on NVIDIA GPU

### CODE REVIEW

**Comment by davidrohr** [comment]
The pull-request is merged into CALDGEMM's test branch.
I added an optional flag "INCLUDE_CUBLAS" in config.mak, to make usage of cublas optional.

I do not have a CUDA system at hand here, so I couldn't test it yet.

**Comment by TeslaCoder** [comment]
Thanks!  CUBLAS is 60x faster on my test (6024 GFLOPS vs 109 GFLOPS)

System: 
Dual Xeon E5-2690 v2 @ 3.0 GHz ( 20 cores total ), 128 GB system memory, 6x K40 GPU

./dgemm_bench -O 2 -z -m 30720 -n 30720 -w 2048 -h 1024 -o g -_ -p -f
Use -? for help
Initializing CALDGEMM (CUDA Runtime)
Running on 6 devices with 30 bbuffers (ivb113)
Initializing Data... ...alloc A (493440 KB) B (491648 KB) C (7374720 KB)......Done
Doing initial run... Done
Initializing Matrix C
Running Benchmark
Starting DGEMM Run m=30720 k=2048 n=30720 Alpha=-1.000000 Beta=1.000000 LDA=0x808 LDB=0x7808 LDC=0x7808 At=0 Bt=0 ColMajor=0 (A=0x219e00000, B=0x237fe0000, C=0x256000000, (C-A=126091264, (C-B)/w=30728), Linpack=0)
Ratio 0.000000 - gpu_m 30720 gpu_n 30720 - Split n Favor m - Height 1024 (/ 1024), Min Tiling 1024 (0, 0)
Program: caldgemm Sizes - A: 30720x2048 B: 2048x30720 C:30720x30720 (Host: ivb113) System Time 0.642 System Gflops 6024.630

**Comment by TeslaCoder** [comment]
I also tested HPL with multiple nodes, and everything seems to work as expected, except I found I must set  "HPL_PARAMDEFS: -Ca 0" or the result can be incorrect, maybe there is a problem with CUDA and the alternate lookahead, but I did not have time to investigate this further.

**Comment by davidrohr** [comment]
already merged into test branch

**Pull request closed without merging**
